#!/bin/bash
if [ "$#" -lt 1 ]
then
	echo 'program vyzaduje argument'
fi
AN="$1"
#while [ "$AN" != 1 ]
while test "$AN" != 1
do
	echo "$AN"
	#if echo "$AN" | grep '[02468]$' > /dev/null
	if [ 0 == $(echo "$AN%2" | bc) ]
	then
		let AN=AN/2
	else
		AN=$(echo "3*$AN+1" | bc)
	fi
done
echo 1
	
