#!/usr/bin/env python3

import json
import sys

CONVERT=(
    (0,"uname",str),
    (2,"uid",int),
    (3,"gid",int),
    (4,"realname",str),
    (5,"homedir",str),
    (6,"shell",str),
)


zoz=[]
with open("/etc/passwd") as f:
    for line in f:
        value=line.strip().split(":")
        d={}
        for index,key,datatype in CONVERT:
            d[key]=datatype(value[index])
        zoz.append(d)

sys.stdout.write(json.dumps(zoz))
            
