#!/usr/bin/env python3
POKIAL=100

primes=[]
for n in range(2,POKIAL):
    # Tuna by stacilo po sqrt(n)
    for d in range(2,n//2+1):
        if (n % d)==0:
            break
    else:
        primes.append(n)
print(primes)





